### PR TITLE
Remove fission

### PR DESCRIPTION
**Pull request by bmann**
Hey there, we don't use passwords and so our support should be deprecated. LMK if you have questions.

### CODE REVIEW

**Comment by hacdias** [comment]
@bmann is Fission no longer providing a way to add files to their IPFS nodes?

**Comment by hacdias** [comment]
Ping @bmann

**Comment by hacdias** [comment]
After looking a bit closely to fission website, I couldn't find any mention of support for direct IPFS adding for users. Thus, I will merge this.

I'm merging this into remove-fission branch as there's a few issues with the PR but I can't edit the fork.

**Comment by bmann** [comment]
@hacdias sorry, clearly don't have notifications set correctly!

We no longer use passwords, so while this Heroku endpoint is still live for now, it will be revamped. 

Our own CLI is a superset of IPFS-deploy functionality and can also be used with GitHub Actions.

**Pull request merged**
